[project]
name = "sox-noise"
version = "1.0.1"
description = "Noise generator GUI powered by Sound eXchange"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Jonathan Knapp", email = "jaknapp8@gmail.com" },
]
maintainers = [
    { name = "Edward Jazzhands", email = "ed.jazzhands@gmail.com" },
]
license = { text = "Unlicense" }
keywords = ["sox", "noise", "generator", "white noise"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Multimedia :: Sound/Audio :: Sound Synthesis",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
]

[project.urls]
Homepage = "https://github.com/edward-jazzhands/sox-noise"

[project.gui-scripts]
sox-noise = "sox_noise.sox_noise:start"

# Build stuff

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["main.ui", ".version"]

[project.optional-dependencies]
compile = ["PyGObject>=3.42"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]