# .github/workflows/ci-checks.yml

# Remember this only runs on PRs to the main branch, so you can bypass this
# if you push to main directly from your local machine.

name: CI Checks

on:
  pull_request:
    branches:
      - main
  # This allows us to manually trigger the workflow from the GitHub UI
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Setup Nox
        uses: wntrblm/nox@2025.05.01

      # installs Xvfb (virtual X server), fluxbox (lightweight window manager),
      # and wmctrl (used in unit tests to check for the window)
      - name: Install GUI test dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb fluxbox wmctrl

      - name: Run Nox sessions
        run: nox